name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  server-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Lint placeholder
        run: node -e "require('fs').accessSync('server.js'); console.log('server.js exists')"

      - name: Validate env templates exist
        run: |
          test -f .env.example
          test -f .env.production.example
